version: 2

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/my-cards-backend

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout
      - run:
          name: Echo branch name
          command: echo ${CIRCLE_BRANCH}
      - run:
          name: Echo app version
          command: echo $(cat VERSION.txt)
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # Fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Download Dependencies
          command: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run:
          name: Package
          command: mvn verify -Dversion=$(cat VERSION.txt)
      - run:
          name: Move app to upload directory
          command: |
            mkdir -pv ~/my-cards-backend/dist
            cp -v ~/my-cards-backend/target/my-cards-backend-$(cat VERSION.txt).jar ~/my-cards-backend/dist
      - store_test_results:
          path: ~/my-cards-backend/target/surefire-reports
      - store_artifacts:
          path: ~/my-cards-backend/dist